/**
 * Routing + providers. Page agents: DO NOT edit this file — replace your page file in src/pages/
 * (default export) and it is picked up automatically.
 *
 * Provider order (outer → inner): Router → ToastProvider → AuthProvider → SongsProvider → AudioProvider → Layout
 */
import { lazy } from 'react';
import { createBrowserRouter, Outlet, useParams } from 'react-router';
import { RouterProvider } from 'react-router/dom';
import { Layout } from './components/Layout';
import { RouteError } from './components/RouteError';
import { AudioProvider } from './state/AudioProvider';
import { AuthProvider } from './state/AuthProvider';
import { RequireAuth } from './state/RequireAuth';
import { SongsProvider } from './state/SongsProvider';
import { ToastProvider } from './state/ToastProvider';
import HomePage from './pages/HomePage';
import BrowsePage from './pages/BrowsePage';
import LoginPage from './pages/LoginPage';
import SignupPage from './pages/SignupPage';
import NotFoundPage from './pages/NotFoundPage';

// Code-split pages (each default-exports its component).
const SongDetailPage = lazy(() => import('./pages/SongDetailPage'));
const SongFormPage = lazy(() => import('./pages/SongFormPage'));
const ShowsPage = lazy(() => import('./pages/ShowsPage'));
const ShowDetailPage = lazy(() => import('./pages/ShowDetailPage'));
const MatchPage = lazy(() => import('./pages/MatchPage'));
const SpinPage = lazy(() => import('./pages/SpinPage'));
const SetlistPage = lazy(() => import('./pages/SetlistPage'));
const StarPrepPage = lazy(() => import('./pages/StarPrepPage'));
const StatsPage = lazy(() => import('./pages/StatsPage'));
const MePage = lazy(() => import('./pages/MePage'));
const AdminPage = lazy(() => import('./pages/AdminPage'));

/** Providers that need router context (navigation) live inside the root route. */
function Root() {
  return (
    <ToastProvider>
      <AuthProvider>
        <SongsProvider>
          <AudioProvider>
            <Outlet />
          </AudioProvider>
        </SongsProvider>
      </AuthProvider>
    </ToastProvider>
  );
}

// Remount pages when their route param changes (fresh state per song/show).
function SongDetailRoute() {
  const { id } = useParams();
  return <SongDetailPage key={id} />;
}
function SongEditRoute() {
  const { id } = useParams();
  return (
    <RequireAuth>
      <SongFormPage key={`edit-${id}`} />
    </RequireAuth>
  );
}
function ShowDetailRoute() {
  const { slug } = useParams();
  return <ShowDetailPage key={slug} />;
}

export const routes = [
  {
    element: <Root />,
    children: [
      {
        element: <Layout />,
        children: [
          {
            errorElement: <RouteError />,
            children: [
              { index: true, element: <HomePage /> },
              { path: 'songs', element: <BrowsePage /> },
              { path: 'songs/:id', element: <SongDetailRoute /> },
              { path: 'songs/:id/edit', element: <SongEditRoute /> },
              {
                path: 'add',
                element: (
                  <RequireAuth>
                    <SongFormPage key="add" />
                  </RequireAuth>
                ),
              },
              { path: 'shows', element: <ShowsPage /> },
              { path: 'shows/:slug', element: <ShowDetailRoute /> },
              { path: 'match', element: <MatchPage /> },
              { path: 'spin', element: <SpinPage /> },
              { path: 'setlist', element: <SetlistPage /> },
              { path: 'star-prep', element: <StarPrepPage /> },
              { path: 'stats', element: <StatsPage /> },
              { path: 'login', element: <LoginPage /> },
              { path: 'signup', element: <SignupPage /> },
              {
                path: 'me',
                element: (
                  <RequireAuth>
                    <MePage />
                  </RequireAuth>
                ),
              },
              {
                path: 'admin',
                element: (
                  <RequireAuth>
                    <AdminPage />
                  </RequireAuth>
                ),
              },
              { path: '*', element: <NotFoundPage /> },
            ],
          },
        ],
      },
    ],
  },
];

const router = createBrowserRouter(routes);

export default function App() {
  return <RouterProvider router={router} />;
}
